<?php 

	$preset_templates = array(

		/* Homepage Template
		------------------------------------------------------------------------------------------------------------------- */

		'home_page' => array(
				'name' => 'Homepage',
				'contents' => array(
						'aq_block_1' => array( 
							  'horizontal_line' => 'none',
							  'height' => '20',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '1',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '1',
						),
						
						
					)
			),

		/* About Us Template
		------------------------------------------------------------------------------------------------------------------- */

		'about_us' => array(
				'name' => 'About Us Page',
				'contents' => array(
						'aq_block_1' => array( 
							  'title' => '',
							  'heading' => 'h4',
							  'video' => 'http://youtu.be/BG-fC-O_uQE',
							  'type' => 'youtube',
							  'height' => '260',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_video_block',
							  'name' => 'Video Box',
							  'order' => '1',
							  'size' => 'span6',
							  'parent' => '0',
							  'number' => '1',
						),
						'aq_block_2' => array( 
							  'title' => 'About MarketPressThemes',
							  'heading' => 'h3',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. Sed semper metus vitae lectus pulvinar ac sollicitudin magna venenatis. ',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_text_block',
							  'name' => 'Text',
							  'order' => '2',
							  'size' => 'span6',
							  'parent' => '0',
							  'number' => '2',
						),
						'aq_block_3' => array( 
							  'horizontal_line' => 'solid',
							  'height' => '40',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '3',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '3',
						),
						'aq_block_4' => array( 
							  'title' => 'Who We Are',
							  'heading' => 'h3',
							  'pageheader' => '0',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_heading_block',
							  'name' => 'Heading Text',
							  'order' => '1',
							  'size' => 'span7',
							  'parent' => '4',
							  'number' => '5',
						),
						'aq_block_5' => array( 
							  'horizontal_line' => 'none',
							  'height' => '5',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '2',
							  'size' => 'span7',
							  'parent' => '4',
							  'number' => '6',
						),
						'aq_block_6' => array( 
							'tabs' => array( 
									1 => array( 'title' => 'Our Mission' , 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien.' ), 
									2 => array( 'title' => 'Our Philosophy' , 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien.' ), 
									3 => array( 'title' => 'Our Promise' , 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien.' ), 
									4 => array( 'title' => 'Our Guarantees' , 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien.' ) 
								), 
							'type' => 'accordion' , 'bgcolor' => '#ffffff' , 'textcolor' => '#676767' , 'id_base' => 'aq_tabs_block' , 'name' => 'Tabs & Toggles' , 'order' => '3' , 'size' => 'span7' , 'parent' => '4' , 'number' => '7'
						),
						'aq_block_7' => array( 
							  'id_base' => 'aq_column_block',
							  'name' => 'Column',
							  'order' => '4',
							  'size' => 'span7',
							  'parent' => '0',
							  'number' => '4',
						),
						'aq_block_8' => array( 
							  'title' => 'Our Ratings',
							  'heading' => 'h3',
							  'pageheader' => '0',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_heading_block',
							  'name' => 'Heading Text',
							  'order' => '1',
							  'size' => 'span5',
							  'parent' => '5',
							  'number' => '9',
						),
						'aq_block_9' => array( 
							  'horizontal_line' => 'none',
							  'height' => '5',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '2',
							  'size' => 'span5',
							  'parent' => '5',
							  'number' => '10',
						),
						'aq_block_10' => array(
							  'title' => '',
							  'heading' => 'h4',
							  'bars' =>  array(
							    1 => 
							    array(
							      'title' => 'Quality',
							      'width' => '90',
							      'barcolor' => 'blue',
							    ),
							    2 => 
							    array(
							      'title' => 'Delivery',
							      'width' => '90',
							      'barcolor' => 'green',
							    ),
							    3 => 
							    array(
							      'title' => 'Price',
							      'width' => '95',
							      'barcolor' => 'yellow',
							    ),
							    4 => 
							    array(
							      'title' => 'Customer Service',
							      'width' => '100',
							      'barcolor' => 'red',
							    ),
							  ),
							  'type' => 'animated',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_progress_block',
							  'name' => 'Progress Bars',
							  'order' => '3',
							  'size' => 'span5',
							  'parent' => '5',
							  'number' => '11',
						),
						'aq_block_11' => array( 
							  'id_base' => 'aq_column_block',
							  'name' => 'Column',
							  'order' => '5',
							  'size' => 'span5',
							  'parent' => '0',
							  'number' => '8',
						),
						'aq_block_12' => array( 
							  'horizontal_line' => 'solid',
							  'height' => '40',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '6',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '12',
						),
						'aq_block_13' => array( 
							  'title' => 'Meet The People Behind MarketPressThemes',
							  'heading' => 'h2',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. Sed semper metus vitae lectus pulvinar ac sollicitudin magna venenatis. ',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_text_block',
							  'name' => 'Text',
							  'order' => '7',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '13',
						),
						'aq_block_14' => array( 
							  'horizontal_line' => 'none',
							  'height' => '5',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '8',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '14',
						),
						'aq_block_15' => array( 
							  'title' => 'The Owl',
							  'position' => 'CEO / FOUNDER',
							  'media' => '',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. ',
							  'fb' => 'http://www.facebook.com',
							  'twitter' => 'http://www.twitter.com',
							  'email' => 'email@website.com',
							  'bgcolor' => '#F8F8F8',
							  'textcolor' => '#676767',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_staff_block',
							  'name' => 'Team Member',
							  'order' => '9',
							  'size' => 'span4',
							  'parent' => '0',
							  'number' => '15',
						),
						'aq_block_16' => array( 
							  'title' => 'Kookaburra',
							  'position' => 'Marketing Manager',
							  'media' => '',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. ',
							  'fb' => 'http://www.facebook.com',
							  'twitter' => 'http://www.twitter.com',
							  'email' => 'email@website.com',
							  'bgcolor' => '#F8F8F8',
							  'textcolor' => '#676767',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_staff_block',
							  'name' => 'Team Member',
							  'order' => '10',
							  'size' => 'span4',
							  'parent' => '0',
							  'number' => '16',
						),
						'aq_block_17' => array( 
							  'title' => 'The Parrot',
							  'position' => 'Customer Service',
							  'media' => '',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. ',
							  'fb' => 'http://www.facebook.com',
							  'twitter' => 'http://www.twitter.com',
							  'email' => 'email@website.com',
							  'bgcolor' => '#F8F8F8',
							  'textcolor' => '#676767',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_staff_block',
							  'name' => 'Team Member',
							  'order' => '11',
							  'size' => 'span4',
							  'parent' => '0',
							  'number' => '17',
						),
					)
			), 

		/* FAQ Page Template
		------------------------------------------------------------------------------------------------------------------- */

		'faq_page' => array(
				'name' => 'FAQ Page',
				'contents' => array(
						'aq_block_1' => array( 
							  'title' => 'We have answered your burning questions',
							  'heading' => 'h3',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elit metus, lobortis sed tincidunt vel, lobortis ut nunc. Etiam libero ante, aliquet eu bibendum ac, pretium eu sapien. In dictum purus sed ipsum vestibulum congue. Sed semper metus vitae lectus pulvinar ac sollicitudin magna venenatis. ',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_text_block',
							  'name' => 'Text',
							  'order' => '1',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '1',
						),
						'aq_block_2' => array( 
							  'horizontal_line' => 'none',
							  'height' => '5',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '2',
							  'size' => 'span12',
							  'parent' => '0',
							  'number' => '2',
						),
						'aq_block_3' => array( 
							'tabs' => array( 
									1 => array( 'title' => 'Lorem ipsum dolor sit amet, consectetur adipiscing' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' ), 
									2 => array( 'title' => 'Curabitur mattis ipsum at sapien dapibus' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' ), 
									3 => array( 'title' => 'Nulla et quam sed lectus suscipit dapibus' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' ), 
									4 => array( 'title' => 'Maecenas sagittis imperdiet neque' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' ),
									5 => array( 'title' => 'Duis nec eros nulla' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' ),
									6 => array( 'title' => 'Vivamus iaculis justo nec ante ornare' , 'content' => 'Phasellus dolor tellus, vulputate in volutpat ut, cursus eget ligula. Curabitur velit arcu, pellentesque ac placerat a, faucibus nec nunc. Mauris ut turpis a dolor imperdiet vestibulum. Ut aliquet semper tincidunt. Cras pretium diam ac metus porta et posuere augue aliquet.' )
								), 
							'type' => 'accordion' , 'bgcolor' => '#ffffff' , 'textcolor' => '#676767' , 'id_base' => 'aq_tabs_block' , 'name' => 'Tabs & Toggles' , 'order' => '3' , 'size' => 'span12' , 'parent' => '0' , 'number' => '3'
						),
					)
			),

		/* Contact Page Template
		------------------------------------------------------------------------------------------------------------------- */

		'contact_page' => array(
				'name' => 'Contact Page',
				'contents' => array(
						'aq_block_1' => array( 
							  'title' => 'Business Info',
							  'heading' => 'h4',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus ante, laoreet quis varius accumsan, luctus sit amet massa.',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_text_block',
							  'name' => 'Text',
							  'order' => '1',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '2',
						),
						'aq_block_2' => array( 
							  'horizontal_line' => 'none',
							  'height' => '0',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '2',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '3',
						),
						'aq_block_3' => array( 
							  'title' => '',
							  'heading' => 'h4',
							  'items' => array(
							    1 => array(
							      'title' => 'Company Name',
							      'content' => 'Company Name',
							      'icontype' => 'icon-home',
							      'iconcolor' => 'black',
							    ),
							    2 => array(
							      'title' => 'address',
							      'content' => 'Somewhere in the planet Earth',
							      'icontype' => 'icon-map-marker',
							      'iconcolor' => 'black',
							    ),
							    3 => array(
							      'title' => 'phone',
							      'content' => '1-800-12-3456',
							      'icontype' => 'icon-user',
							      'iconcolor' => 'black',
							    ),
							    4 => array(
							      'title' => 'fax',
							      'content' => '1-800-78-8912',
							      'icontype' => 'icon-print',
							      'iconcolor' => 'black',
							    ),
							    5 => array(
							      'title' => 'email',
							      'content' => 'email@website.com',
							      'icontype' => 'icon-envelope',
							      'iconcolor' => 'black',
							    ),
							    6 => array(
							      'title' => 'website',
							      'content' => 'www.Website.com',
							      'icontype' => 'icon-globe',
							      'iconcolor' => 'black',
							    ),
							  ),
							  'type' => 'icon',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_list_block',
							  'name' => 'List',
							  'order' => '3',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '4',
						),
						'aq_block_4' => array( 
							  'horizontal_line' => 'none',
							  'height' => '0',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '4',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '5',
						),
						'aq_block_5' => array( 
							  'title' => 'Location Map',
							  'heading' => 'h4',
							  'pageheader' => '0',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_heading_block',
							  'name' => 'Heading Text',
							  'order' => '5',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '6',
						),
						'aq_block_6' => array( 
							  'horizontal_line' => 'none',
							  'height' => '0',
							  'line_color' => '#e5e5e5',
							  'id_base' => 'aq_separator_block',
							  'name' => 'Separator',
							  'order' => '6',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '7',
						),
						'aq_block_7' => array( 
							  'title' => '',
							  'heading' => 'h3',
							  'address' => 'Kuala Lumpur City Centre, 50088 Kuala Lumpur, Malaysia',
							  'width' => '360',
							  'height' => '270',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_map_block',
							  'name' => 'Google Map',
							  'order' => '7',
							  'size' => 'span4',
							  'parent' => '1',
							  'number' => '8',
						),
						'aq_block_8' => array( 
							  'id_base' => 'aq_column_block',
							  'name' => 'Column',
							  'order' => '1',
							  'size' => 'span4',
							  'parent' => '0',
							  'number' => '1',
						),
						'aq_block_9' => array( 
							  'title' => 'Get In Touch With Us!',
							  'heading' => 'h4',
							  'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus ante, laoreet quis varius accumsan, luctus sit amet massa. Aenean nec arcu justo. Donec in nunc magna. Donec rhoncus nisl non tellus iaculis vestibulum. Suspendisse et diam enim',
							  'id' => '',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_text_block',
							  'name' => 'Text',
							  'order' => '1',
							  'size' => 'span8',
							  'parent' => '2',
							  'number' => '10',
						),
						'aq_block_10' => array( 
							  'title' => '',
							  'sendtoemail' => '',
							  'btntext' => 'Send Message',
							  'btnsize' => 'large',
							  'btncolor' => 'black',
							  'class' => '',
							  'style' => '',
							  'id_base' => 'aq_contact_block',
							  'name' => 'Contact Form',
							  'order' => '2',
							  'size' => 'span8',
							  'parent' => '2',
							  'number' => '11',
						),
						'aq_block_11' => array( 
							  'id_base' => 'aq_column_block',
							  'name' => 'Column',
							  'order' => '2',
							  'size' => 'span8',
							  'parent' => '0',
							  'number' => '9',
						),
					)
			),

	); // end - $preset_templates

	$preset_templates = apply_filters( 'aqpb_preset_templates_variables' , $preset_templates );